title: Nicole Peternel
email: nkpeternel@berkeley.edu
description: "Personal Website"
bio: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicolepeternel.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  npeternel
facebook_username: nicki.peternel
linkedin_username: nicole-peternel

# Build settings
markdown: kramdown
sass:
    sass_dir: ./_sass
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - bootstrap-sass
  - breakpoint
exclude:
  - Gemfile
  - Gemfile.lock
