title: Nicki Peternel's Personal Website
email: nkpeternel@berkeley.edu
description: "Personal Website"
bio: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nickip.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  npeternel
linkedin_username: npeternel

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
